name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  pillarCode:
    description: 'Pillar Code'
    required: false
  environmentName:
    description: 'Environment Name'
    required: true
  clientId:
    description: 'Azure Client Id'
    required: false
  subscriptionId:
    description: 'Azure Subscription Id'
    required: false
  tenantId:
    description: 'Azure Tenant Id'
    required: false

# Define your outputs here.
outputs:
  clientId:
    description: 'Azure Client Id'
  subscriptionId:
    description: 'Azure Subscription Id'
  tenantId:
    description: 'Azure Tenant Id'
  pulumiStateSubscriptionId:
    description: 'Pulumi State Subscription Id'

runs:
  using: node20
  main: dist/index.js
